common:
  # 保存したいURL
  download_uri: 'http://example.localhost/'

  # 以下無視リスト
  # bootstrap等 cdnから取ってくるものなどは、ローカルに保存せず元URLを指定する。
  # 下記が無視する条件
  # //から始まる場合はドメイン
  # /から始まる場合は絶対パス
  # それ以外から始まる場合はパス内に特定文字列が含まれている場合
  ignore_list:
    - '//googleapis.com'
    - '//googletagmanager.com'
    - '//apple.com'
    - '//unpkg.com'
    - '//fontawesome.com'
    - '//fonts.gstatic.com'
    - '//youtube.com'
    - '//facebook.com'
    - '//twitter.com'
    - '//cdn.jsdelivr.net'
    - '//cdn.rawgit.com'
    - '//cdnjs.cloudflare.com'
    - '//code.jquery.com'
    - '/unknown'
    - 'cmd='

  # 保存先パス
  save_path: './localhost-saved'

  # 検索の深さ
  search_depth: 5

  # HTMLのエンコーディング(稀にあるeucのサイトを保存するために活用する)
  encoding: 'utf-8'

  # マルチスレッドで動作させる。(メモリ不足や変な不具合が出る場合はfalseにする事。)
  # 主にtrueにすると若干実行速度が速くなるかもしれない。
  multithread: true

  # baseタグを基準とした相対パスを作成する場合 trueを設定する。
  basetag_relative: true
